[package]
name = "weekend-raytracer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main1"
path = "src/main1.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
